### ISSUE TITLE
run the train.py and test.py seems to run the code of Structural-RNN instead of MPC?

### ISSUE THREAD

**Issue by MandyZhang4869** [sriyash421/Pred2Nav#2]
I am sorry to bother you, but I would like to konw how to run the code of MPC based on the paper "From Crowd Prediction Models to Robot Navigation in Crowds" and "Winding Through: Crowd Navigation via Topological Invariance"

**Comment by sriyash421** [comment]
Hi, I have updated the README. Please run the run_eval.py to run the MPC code. train and test code wll run the SRNN code. Please let me know if you have anymore doubts

**Comment by MandyZhang4869** [comment]
I ran  run_eval.py，and got the following error，what's the 0_trajectory.npy for？how can I generate it？
`final_real
Traceback (most recent call last):
  File "run_eval.py", line 13, in <module>
    main_config(config)
  File "/Pred2Nav/evaluation_mpc.py", line 157, in main_config
    evaluate(config, env, False)
  File "/Pred2Nav/evaluation_mpc.py", line 44, in evaluate
    obs = env.reset()
  File "/Pred2Nav/crowd_sim/envs/crowd_sim.py", line 625, in reset
    self.generate_robot_humans(phase)
  File "/Pred2Nav/crowd_sim/envs/crowd_sim.py", line 589, in generate_robot_humans
    self.generate_random_human_position(human_num=human_num)
  File "/Pred2Nav/crowd_sim/envs/crowd_sim.py", line 212, in generate_random_human_position
    self.humans.append(self.generate_real_human(i))
  File "/Pred2Nav/crowd_sim/envs/crowd_sim.py", line 239, in generate_real_human
    human.policy.reset(i, self.episode)
  File "/Pred2Nav/crowd_nav/policy/realhuman.py", line 16, in reset
    temp = np.load(os.path.join('/home/sriyash421/PRL22/CrowdNav_DSRNN/crowd_nav/policy/cv_trajs2', f'{ep}_trajectory.npy'))
  File "/home/mandy18/anaconda3/envs/mpc_sgan/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/sriyash421/PRL22/CrowdNav_DSRNN/crowd_nav/policy/cv_trajs2/0_trajectory.npy'`
